#api_platform:
#    title: Hello API Platform
#    version: 1.0.0
#    formats:
#        jsonld: ['application/ld+json']
#    docs_formats:
#        jsonld: ['application/ld+json']
#        jsonopenapi: ['application/vnd.openapi+json']
#        html: ['text/html']
#    defaults:
#        stateless: true
#        cache_headers:
#            vary: ['Content-Type', 'Authorization', 'Origin']
#        extra_properties:
#            standard_put: true
#            rfc_7807_compliant_errors: true
#    event_listeners_backward_compatibility_layer: false
#    keep_legacy_inflector: false

#config/packages/api_platform.yaml
api_platform:
    # The title of the API.
    title: 'Hello API Platform'

    # The description of the API.
    description: 'Hello API Platform description'

    # The version of the API.
    version: '1.0.0'

    # Set this to false if you want Webby to disappear.
    show_webby: false

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            Bearer:
                name: AUTH-TOKEN
                type: header
